// <auto-generated />
using System;
using CampusServicesPortal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampusServicesPortal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260731100518_InitialCleanDatabaseSchema")]
    partial class InitialCleanDatabaseSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CampusServicesPortal.Models.CertificateRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CertificateTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CertificateTypeId");

                    b.HasIndex("StudentId");

                    b.ToTable("CertificateRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CertificateTypeId = 1,
                            Reason = "Required for visa application submission requirements.",
                            RequestedAt = new DateTime(2026, 7, 30, 10, 5, 16, 712, DateTimeKind.Utc).AddTicks(4673),
                            Status = "Pending",
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            CertificateTypeId = 2,
                            Reason = "Applying for a software engineering internship program.",
                            RequestedAt = new DateTime(2026, 7, 26, 10, 5, 16, 712, DateTimeKind.Utc).AddTicks(4674),
                            Status = "ReadyForCollection",
                            StudentId = 3
                        });
                });

            modelBuilder.Entity("CampusServicesPortal.Models.CertificateType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CertificateTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Bonafide Certificate"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Official Transcript"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Completion Letter"
                        });
                });

            modelBuilder.Entity("CampusServicesPortal.Models.Complaint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StudentId");

                    b.ToTable("Complaints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 7, 29, 10, 5, 16, 712, DateTimeKind.Utc).AddTicks(4648),
                            Description = "Room B-101 ceiling fan is vibrating aggressively and generating loud noises.",
                            Status = "Pending",
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 7, 27, 10, 5, 16, 712, DateTimeKind.Utc).AddTicks(4655),
                            Description = "Wi-Fi connectivity is unavailable in the Engineering block common room area.",
                            ResolutionNote = "IT department is assigning an engineer to inspect the access point router.",
                            Status = "In Progress",
                            StudentId = 2
                        });
                });

            modelBuilder.Entity("CampusServicesPortal.Models.ComplaintCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ComplaintCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Hostel Maintenance"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Academic Issues"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Network & Wi-Fi"
                        });
                });

            modelBuilder.Entity("CampusServicesPortal.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 200,
                            Description = "Networking meet and greet.",
                            EndDateTime = new DateTime(2026, 9, 10, 16, 0, 0, 0, DateTimeKind.Utc),
                            StartDateTime = new DateTime(2026, 9, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Annual University Career Fair 2026",
                            VenueId = 1
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 800,
                            Description = "Annual tournament.",
                            EndDateTime = new DateTime(2026, 10, 18, 18, 0, 0, 0, DateTimeKind.Utc),
                            StartDateTime = new DateTime(2026, 10, 15, 8, 30, 0, 0, DateTimeKind.Utc),
                            Title = "Inter-Faculty Cricket Championship",
                            VenueId = 2
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 45,
                            Description = "Guest lecture from industry specialists.",
                            EndDateTime = new DateTime(2026, 8, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            StartDateTime = new DateTime(2026, 8, 20, 14, 0, 0, 0, DateTimeKind.Utc),
                            Title = "AI & Ethics Tech Talk",
                            VenueId = 3
                        });
                });

            modelBuilder.Entity("CampusServicesPortal.Models.EventRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("StudentId");

                    b.ToTable("EventRegistrations");
                });

            modelBuilder.Entity("CampusServicesPortal.Models.Faculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Faculties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Faculty of Computing"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Faculty of Engineering"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Faculty of Business"
                        });
                });

            modelBuilder.Entity("CampusServicesPortal.Models.FeePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BillingPeriod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("FeeTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FeeTypeId");

                    b.HasIndex("StudentId");

                    b.ToTable("FeePayments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 45000.00m,
                            BillingPeriod = "2026 - Sem 1",
                            Description = "Academic Tuition Fees",
                            FeeTypeId = 1,
                            PaidAt = new DateTime(2026, 7, 11, 10, 5, 16, 712, DateTimeKind.Utc).AddTicks(4708),
                            Status = "Paid",
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 1500.00m,
                            BillingPeriod = "2026 - Sem 1",
                            Description = "Fine issued for damaged computer mouse hardware.",
                            FeeTypeId = 4,
                            Status = "Outstanding",
                            StudentId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 5000.00m,
                            BillingPeriod = "2026 - Sem 1",
                            Description = "General Amenities Fee run.",
                            FeeTypeId = 2,
                            Status = "Outstanding",
                            StudentId = 2
                        },
                        new
                        {
                            Id = 4,
                            Amount = 45000.00m,
                            BillingPeriod = "2026 - Sem 1",
                            Description = "Academic Tuition Fees",
                            FeeTypeId = 1,
                            Status = "Outstanding",
                            StudentId = 3
                        });
                });

            modelBuilder.Entity("CampusServicesPortal.Models.FeeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("FeeTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tuition Fee"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Semester Fee"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Exam Fee"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Lab Fine"
                        });
                });

            modelBuilder.Entity("CampusServicesPortal.Models.Hostel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Hostels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Jayathilake Hall (Boys)"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Sangamitta Hall (Girls)"
                        });
                });

            modelBuilder.Entity("CampusServicesPortal.Models.HostelApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedRoomId")
                        .HasColumnType("int");

                    b.Property<int>("PreferredHostelId")
                        .HasColumnType("int");

                    b.Property<string>("SpecialRequirements")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("TermSemester")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedRoomId");

                    b.HasIndex("PreferredHostelId");

                    b.HasIndex("StudentId");

                    b.ToTable("HostelApplications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedRoomId = 1,
                            PreferredHostelId = 1,
                            SpecialRequirements = "Prefer lower floor room.",
                            Status = "RoomAssigned",
                            StudentId = 1,
                            TermSemester = "Year 1 - Sem 1"
                        },
                        new
                        {
                            Id = 2,
                            PreferredHostelId = 2,
                            Status = "Pending",
                            StudentId = 3,
                            TermSemester = "Year 1 - Sem 1"
                        });
                });

            modelBuilder.Entity("CampusServicesPortal.Models.Lab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LabType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TotalColumns")
                        .HasColumnType("int");

                    b.Property<int?>("TotalRows")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Labs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 30,
                            IsActive = true,
                            LabType = "Computer",
                            Name = "Main Computer Lab 01",
                            TotalColumns = 6,
                            TotalRows = 5
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 20,
                            IsActive = true,
                            LabType = "Science",
                            Name = "Chemistry Lab A"
                        });
                });

            modelBuilder.Entity("CampusServicesPortal.Models.LabBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LabId")
                        .HasColumnType("int");

                    b.Property<int?>("SeatId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("TimeSlot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("LabId");

                    b.HasIndex("SeatId");

                    b.HasIndex("StudentId");

                    b.ToTable("LabBookings");
                });

            modelBuilder.Entity("CampusServicesPortal.Models.LabSeat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColumnIndex")
                        .HasColumnType("int");

                    b.Property<bool>("IsBroken")
                        .HasColumnType("bit");

                    b.Property<int>("LabId")
                        .HasColumnType("int");

                    b.Property<int>("RowIndex")
                        .HasColumnType("int");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("LabId");

                    b.ToTable("LabSeats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColumnIndex = 0,
                            IsBroken = false,
                            LabId = 1,
                            RowIndex = 0,
                            SeatNumber = "PC-01"
                        },
                        new
                        {
                            Id = 2,
                            ColumnIndex = 1,
                            IsBroken = false,
                            LabId = 1,
                            RowIndex = 0,
                            SeatNumber = "PC-02"
                        },
                        new
                        {
                            Id = 3,
                            ColumnIndex = 3,
                            IsBroken = false,
                            LabId = 1,
                            RowIndex = 0,
                            SeatNumber = "PC-03"
                        },
                        new
                        {
                            Id = 4,
                            ColumnIndex = 0,
                            IsBroken = true,
                            LabId = 1,
                            RowIndex = 1,
                            SeatNumber = "PC-04"
                        });
                });

            modelBuilder.Entity("CampusServicesPortal.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 30, 10, 5, 16, 712, DateTimeKind.Utc).AddTicks(4731),
                            IsRead = false,
                            Message = "An outstanding Lab Fine of LKR 1,500.00 has been assigned to your billing dashboard.",
                            StudentId = 1,
                            Type = "FeeAssignmentCreated"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 31, 10, 5, 16, 712, DateTimeKind.Utc).AddTicks(4733),
                            IsRead = false,
                            Message = "Your Transcript request is ready for physical collection at the registrar office desk.",
                            StudentId = 3,
                            Type = "CertificateStatusUpdated"
                        });
                });

            modelBuilder.Entity("CampusServicesPortal.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("CampusServicesPortal.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HostelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("HostelId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HostelId = 1,
                            IsActive = true,
                            MaxCapacity = 4,
                            RoomNumber = "B-101"
                        },
                        new
                        {
                            Id = 2,
                            HostelId = 1,
                            IsActive = true,
                            MaxCapacity = 2,
                            RoomNumber = "B-102"
                        },
                        new
                        {
                            Id = 3,
                            HostelId = 2,
                            IsActive = true,
                            MaxCapacity = 4,
                            RoomNumber = "G-201"
                        });
                });

            modelBuilder.Entity("CampusServicesPortal.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactDetails")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmailVerificationTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("bit");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("IndexNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.HasIndex("IndexNumber")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactDetails = "+94771234567",
                            EmailVerified = true,
                            FacultyId = 1,
                            FullName = "Kamal Perera",
                            IndexNumber = "STU/2026/001",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            ContactDetails = "+94719876543",
                            EmailVerified = true,
                            FacultyId = 2,
                            FullName = "Nimal Silva",
                            IndexNumber = "STU/2026/002",
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            ContactDetails = "+94751112223",
                            EmailVerified = true,
                            FacultyId = 1,
                            FullName = "Anusha Fernando",
                            IndexNumber = "STU/2026/003",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("CampusServicesPortal.Models.StudentMasterList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("IndexNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IndexNumber")
                        .IsUnique();

                    b.ToTable("StudentMasterLists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FacultyId = 1,
                            FullName = "Kamal Perera",
                            IndexNumber = "STU/2026/001"
                        },
                        new
                        {
                            Id = 2,
                            FacultyId = 2,
                            FullName = "Nimal Silva",
                            IndexNumber = "STU/2026/002"
                        },
                        new
                        {
                            Id = 3,
                            FacultyId = 1,
                            FullName = "Anusha Fernando",
                            IndexNumber = "STU/2026/003"
                        });
                });

            modelBuilder.Entity("CampusServicesPortal.Models.SystemSetting", b =>
                {
                    b.Property<string>("SettingKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SettingKey");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            SettingKey = "reservation-hold-minutes",
                            SettingValue = "15"
                        });
                });

            modelBuilder.Entity("CampusServicesPortal.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 31, 10, 5, 16, 712, DateTimeKind.Utc).AddTicks(4515),
                            Email = "admin@university.edu.lk",
                            IsActive = true,
                            PasswordHash = "$2a$11$qRzP42b3mY0b6uX8...",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 31, 10, 5, 16, 712, DateTimeKind.Utc).AddTicks(4519),
                            Email = "kamal@student.university.ac.lk",
                            IsActive = true,
                            PasswordHash = "$2a$11$w8h9x7y6z5u...",
                            Role = "Student"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 31, 10, 5, 16, 712, DateTimeKind.Utc).AddTicks(4520),
                            Email = "nimal@student.university.ac.lk",
                            IsActive = true,
                            PasswordHash = "$2a$11$w8h9x7y6z5u...",
                            Role = "Student"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 31, 10, 5, 16, 712, DateTimeKind.Utc).AddTicks(4522),
                            Email = "anusha@student.university.ac.lk",
                            IsActive = true,
                            PasswordHash = "$2a$11$w8h9x7y6z5u...",
                            Role = "Student"
                        });
                });

            modelBuilder.Entity("CampusServicesPortal.Models.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 250,
                            IsActive = true,
                            Name = "Wimaladharma Main Auditorium",
                            Type = "Event Hall"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 1000,
                            IsActive = true,
                            Name = "University Playground",
                            Type = "Open Space"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 50,
                            IsActive = true,
                            Name = "Mini Seminar Room B",
                            Type = "Event Hall"
                        });
                });

            modelBuilder.Entity("CampusServicesPortal.Models.CertificateRequest", b =>
                {
                    b.HasOne("CampusServicesPortal.Models.CertificateType", "CertificateType")
                        .WithMany()
                        .HasForeignKey("CertificateTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampusServicesPortal.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CertificateType");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CampusServicesPortal.Models.Complaint", b =>
                {
                    b.HasOne("CampusServicesPortal.Models.ComplaintCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampusServicesPortal.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CampusServicesPortal.Models.Event", b =>
                {
                    b.HasOne("CampusServicesPortal.Models.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("CampusServicesPortal.Models.EventRegistration", b =>
                {
                    b.HasOne("CampusServicesPortal.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampusServicesPortal.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CampusServicesPortal.Models.FeePayment", b =>
                {
                    b.HasOne("CampusServicesPortal.Models.FeeType", "FeeType")
                        .WithMany()
                        .HasForeignKey("FeeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampusServicesPortal.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FeeType");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CampusServicesPortal.Models.HostelApplication", b =>
                {
                    b.HasOne("CampusServicesPortal.Models.Room", "AssignedRoom")
                        .WithMany()
                        .HasForeignKey("AssignedRoomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CampusServicesPortal.Models.Hostel", "PreferredHostel")
                        .WithMany()
                        .HasForeignKey("PreferredHostelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampusServicesPortal.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedRoom");

                    b.Navigation("PreferredHostel");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CampusServicesPortal.Models.LabBooking", b =>
                {
                    b.HasOne("CampusServicesPortal.Models.Lab", "Lab")
                        .WithMany()
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampusServicesPortal.Models.LabSeat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CampusServicesPortal.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lab");

                    b.Navigation("Seat");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CampusServicesPortal.Models.LabSeat", b =>
                {
                    b.HasOne("CampusServicesPortal.Models.Lab", "Lab")
                        .WithMany("Seats")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lab");
                });

            modelBuilder.Entity("CampusServicesPortal.Models.Notification", b =>
                {
                    b.HasOne("CampusServicesPortal.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CampusServicesPortal.Models.PasswordResetToken", b =>
                {
                    b.HasOne("CampusServicesPortal.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CampusServicesPortal.Models.Room", b =>
                {
                    b.HasOne("CampusServicesPortal.Models.Hostel", "Hostel")
                        .WithMany("Rooms")
                        .HasForeignKey("HostelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hostel");
                });

            modelBuilder.Entity("CampusServicesPortal.Models.Student", b =>
                {
                    b.HasOne("CampusServicesPortal.Models.Faculty", null)
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampusServicesPortal.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("CampusServicesPortal.Models.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CampusServicesPortal.Models.Hostel", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("CampusServicesPortal.Models.Lab", b =>
                {
                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
